erDiagram
    field {
        int ID PK
        int ParentID
        varchar Name
        varchar Handle
        enum Type         
        %%  plain_text, rich_text, link, assets
        longtext Description
    }
    page {
        int ID PK
        varchar Title
        varchar Slug
        longtext Content
        int AuthorID FK
    }
    model {
        int ID PK
        varchar Name
        varchar FilePath
        enum Category
    }
    model_meta {
        int ID PK
        int ModelID FK
        varchar MetaKey
        longtext MetaValue
    }
    skirt_pattern {
        int ID PK
        json Attribute
    }
    user {
        int ID PK
        varchar Username
        varchar Email
        varchar Password
    }
    page_field {
        int ID PK
        int PageID FK
        int FieldID FK
        varchar FieldName
        varchar FieldHandle
        enum FieldType    
        %% plain_text, rich_text, link, assets
    }
    page_field_meta {
        int ID PK
        int PFID FK
        varchar MetaKey
        longtext MetaValue
    }
    page_meta {
        int ID PK
        int PageID FK
        varchar MetaKey
        longtext MetaValue
    }

    model ||--o{ model_meta : ""
    model ||--|| model_meta : "1-1"
    page ||--o{ page_field : ""
    field ||--o{ page_field : ""
    page ||--o| user : "author"
    page ||--o{ page_meta : ""
    page_field ||--o{ page_field_meta : ""
