erDiagram
    field {
        int ID PK
        int ParentID
        varchar Name
        varchar Handle
        enum Type         
        %%  plain_text, rich_text, link, assets
        longtext Description
    }
    page {
        int ID PK
        varchar Title
        varchar Slug
        longtext Content
    }
    model {
        int ID PK
        varchar Name
        varchar FilePath
        enum Category
    }
    model_meta {
        int ModelID "PK,FK"
        json OtherAttributes
    }
    skirt_pattern {
        int ID PK
        json Attribute
    }
    user {
        int ID PK
        varchar Username
        varchar Email
        varchar Password
    }
    page_field {
        int PageID
        int FieldID
        varchar FieldName
        varchar FieldHandle
        enum FieldType    
        %% plain_text, rich_text, link, assets
        longtext Content
    }

    model ||--|| model_meta : "1-1"
    page ||--o{ page_field : ""
    field ||--o{ page_field : ""
